server {
    listen 80;
    server_tokens off;

    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header Cache-Control "no-store" always;

    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=(), payment=(), usb=()" always;
    add_header Cross-Origin-Opener-Policy "same-origin" always;
    add_header Cross-Origin-Resource-Policy "same-origin" always;
    add_header Cross-Origin-Embedder-Policy "require-corp" always;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location = /api/arch {
        default_type application/json;
        add_header Cache-Control "no-store";
        return 200 '{"arch":"nanoservices-kubernetes","component":"nginx-configmap"}';
    }

    location = /api/ping {
        default_type application/json;
        add_header Cache-Control "no-store";
        return 200 '{"ok":true}';
    }

    location = /api/checkout {
        proxy_http_version 1.1;
        proxy_set_header Host localhost;
        proxy_set_header Connection "";
        proxy_set_header X-Request-Id $http_x_request_id;
        proxy_pass http://checkout-svc:3003/api/checkout;
    }
}
